services:
  web:
    container_name: payLater # TODO: chang me for new instance
    build: .
    #    image: "traefik/whoami"
    environment:
      SHOPIFY_APP_URL: "https://paylater.cpro-server.de"
      SHOPIFY_SHOP: "helge-test.myshopify.com"
      HOST: "0.0.0.0"
      SHOPIFY_API_KEY: "4fd4f1171fc3d999235a8da23786d5d8"
      SHOPIFY_API_SECRET: "f25b4f87a8cd2cee49e4d8981af1ac39"
      SCOPES: "write_products,write_orders,read_orders"
      DATABASE_URL: "mysql://root:1WrPZqlCnk4CHbpd31cq@payLater_db:3306/payLater" # TODO: change me for new instance
    labels:
      - traefik.enable=true
      - traefik.http.routers.paylater.rule=Host(`paylater.cpro-server.de`) # TODO: change me for new instance
      - traefik.http.routers.paylater.entrypoints=websecure
      - traefik.http.routers.paylater.tls.certresolver=letsencrypt
    #   - traefik.http.services.ebike.loadbalancer.server.port=3000
    restart: unless-stopped
    networks:
      - web
      - intern
  # might be needed, but seems to work without
  #    dns:
  #      - 8.8.8.8
  db:
    container_name: payLater_db # TODO: change me for new instance
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    image: mariadb:10
    restart: unless-stopped
    volumes:
      - ../databaseData/payLater:/var/lib/mysql # TODO: change me for new instnaces
    environment:
      - MARIADB_INITDB_SKIP_TZINFO=true
        #  - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=1WrPZqlCnk4CHbpd31cq # TODO: you may change me
    networks:
      - intern

networks:
  web:
    external: true
  intern:
    external: false
