# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "809a6d540ff4edfbd302c10e2895d03a"
name = "paylater"
application_url = "https://paylater.cpro-server.de"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "helge-test.myshopify.com"
include_config_on_deploy = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_orders, write_products"

[auth]
redirect_urls = [
  "https://paylater.cpro-server.de/auth/callback",
  "https://paylater.cpro-server.de/auth/shopify/callback",
  "https://paylater.cpro-server.de/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
