# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pay-later"
client_id = "4fd4f1171fc3d999235a8da23786d5d8"
application_url = "https://target-liberal-failures-katrina.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://target-liberal-failures-katrina.trycloudflare.com/auth/callback",
  "https://target-liberal-failures-katrina.trycloudflare.com/auth/shopify/callback",
  "https://target-liberal-failures-katrina.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "helge-test.myshopify.com"
